### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by zhouhao-learning** [tensorflow/adanet#11]
When I installed `bazel`, I executed the `bazel test -c opt //...` command and got a failed test.
```
external/com_google_protobuf/python: warning: directory does not exist.
FAIL: //adanet/core:estimator_test (shard 3 of 20) (see /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_3_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 4 of 20) (see /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_4_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 6 of 20) (see /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_6_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 12 of 20) (see /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_12_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 8 of 20) (see /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_8_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 14 of 20) (see /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_14_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 7 of 20) (see /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_7_of_20/test.log)
FAIL: //adanet/core:estimator_test (shard 5 of 20) (see /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_5_of_20/test.log)

FAILED: //adanet/core:estimator_test (Summary)
      /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_3_of_20/test.log
      /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_4_of_20/test.log
      /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_6_of_20/test.log
      /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_12_of_20/test.log
      /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_8_of_20/test.log
      /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_14_of_20/test.log
      /home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/estimator_test/shard_7_of_20/test.log

```
My tensorflow version is 1.7,What is the problem?

**Comment by cweill** [comment]
Could you please share the log outputs with the failure?

**Comment by zhouhao-learning** [comment]
@cweill 
This is one of the error logs, and other error logs are similar:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //adanet/core:estimator_test
-----------------------------------------------------------------------------
WARNING: Logging before flag parsing goes to stderr.
W1101 02:08:39.711240 140391769138944 tf_logging.py:126] From /home/zh/anaconda3/envs/Adanet/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
2018-11-01 02:08:44.915166: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/zh/anaconda3/envs/Adanet/lib/python3.5/site-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
.E.
======================================================================
ERROR: test_eval_metrics_binary_classification_head (__main__.EstimatorSummaryWriterTest)
test_eval_metrics_binary_classification_head (__main__.EstimatorSummaryWriterTest)
test_eval_metrics_binary_classification_head(head=<tensorflow.python.estimator.canned.head._BinaryLogisticHeadWithSigmoidCrossEntropyLoss>, want_loss=0.671, want_summaries=['average_loss', 'average_loss/adanet/adanet_weighted_ensemble'])
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/sandbox/linux-sandbox/190/execroot/org_adanet/bazel-out/k8-opt/bin/adanet/core/estimator_test.runfiles/absl_py/absl/testing/parameterized.py", line 256, in bound_param_test
    test_method(self, **testcase_params)
  File "/home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/sandbox/linux-sandbox/190/execroot/org_adanet/bazel-out/k8-opt/bin/adanet/core/estimator_test.runfiles/org_adanet/adanet/core/estimator_test.py", line 955, in test_eval_metrics
    global_subdir,
  File "/home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/sandbox/linux-sandbox/190/execroot/org_adanet/bazel-out/k8-opt/bin/adanet/core/estimator_test.runfiles/org_adanet/adanet/core/estimator_test.py", line 734, in _check_eventfile_for_keyword
    keyword, filenames))
ValueError: Keyword 'architecture/adanet/ensembles/0' not found in path '/home/zh/.cache/bazel/_bazel_zh/a7a1e19f4c4409a4f7aaae78d6eca6b2/sandbox/linux-sandbox/190/execroot/org_adanet/_tmp/964d4db802f4ef8ee3d64c36eb89616a/__main__.EstimatorSummaryWriterTest.test_eval_metrics_binary_classification_head/eval/events*'.

----------------------------------------------------------------------
Ran 3 tests in 113.357s

FAILED (errors=1)
Converted 5 variables to const ops.
```
