### ISSUE TITLE
Multi-output regression

### ISSUE THREAD

**Issue by cicciobyte** [tensorflow/adanet#26]
Hi guys, thanks a lot for the cool piece of work!
I'd like to apply adanet on a multi-output regression problem.
I started from the tutorial 1 trying to apply as few changes as possible.
My understanding is that I probably just need to modify the estimator head.
Unfortunately just changing the label_dimension parameter does not work.

```
 estimator = adanet.Estimator(
      head=tf.contrib.estimator.regression_head(
          label_dimension=LABEL_DIMENSION,
          loss_reduction=tf.losses.Reduction.SUM_OVER_BATCH_SIZE), ...
```
I get that on the very first iteration the model diverges:
`ERROR:tensorflow:Model diverged with loss = NaN.`

Do you have any clue?

error stack:
```
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpsJKglT
INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_global_id_in_cluster': 0, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f50ea95ed50>, '_model_dir': '/tmp/tmpsJKglT', '_protocol': None, '_save_checkpoints_steps': 50000, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_tf_random_seed': 42, '_save_summary_steps': 50000, '_device_fn': None, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_evaluation_master': '', '_eval_distribute': None, '_train_distribute': None, '_master': ''}
INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps 50000 or save_checkpoints_secs None.
INFO:tensorflow:Beginning training AdaNet iteration 0
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2018-11-12 12:56:19.318101: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpsJKglT/model.ckpt.
ERROR:tensorflow:Model diverged with loss = NaN.
Traceback (most recent call last):
  File "test_adanet.py", line 277, in <module>
    results, _ = train_and_evaluate()
  File "test_adanet.py", line 265, in train_and_evaluate
    return tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/adanet/core/estimator.py", line 447, in train
    saving_listeners=saving_listeners)
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1320, in run
    run_metadata=run_metadata))
  File "/opt/miniconda2/envs/python-2.7.10/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 753, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
```

**Comment by cweill** [comment]
I wonder if the `NaN` is due to something else. For example, your datasets may contain `NaNs` or you may be doing some preprocessing that divides by zero or applies `log` to zero. 

If your data is fine, maybe your learning rate is too high, so try something 100x smaller to start.

**Comment by cicciobyte** [comment]
Input numerical issue on my side...
works as expected after removing the `tf.log1p` transformations in `input_fn`
