### ISSUE TITLE
use the demo code train a new dataset (got some problems )

### ISSUE THREAD

**Issue by MingQi-Yuan** [tensorflow/adanet#32]
I got some problems with AdaNet API,when I use the customizing_adanet.ipynb in the 
        adanet/adanet/examples/tutorials/  to train a new dataset, I got some error like this:

InvalidArgumentError: ValueError: `generator` yielded an element of shape (150, 150) where an element of shape () was expected.
Traceback (most recent call last):

  File "D:\Program Files\Anaconda3-5.2\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "D:\Program Files\Anaconda3-5.2\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 454, in generator_py_func
    "of shape %s was expected." % (ret_array.shape, expected_shape))

ValueError: `generator` yielded an element of shape (150, 150) where an element of shape () was expected.

 [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_INT32], token="pyfunc_184", _device="/device:CPU:0"](arg0)]]
 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,150,150,1], [?]], output_types=[DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

     The old data is fashion_mnist, whose image is 28x28, my dataset is 150x150, I've tried lots of ways to adjust the parameters or change the demo code, but it still not works, that's so disappointing！How can I make it？I’d appreciate much if who can do me a favor ！

**Comment by MingQi-Yuan** [comment]
> Do you have a colab you can share with some sample data?

here are the sample data，which has 8 classes，shape of 150x150，in 3 channels.I‘d appreciate much if you can do me a favor！

**Comment by xxllp** [comment]
这个库是不是实验品？
