### ISSUE TITLE
Error running adanet_objective on Windows 7 (Japanese) with Python 3

### ISSUE THREAD

**Issue by tanaka-jp** [tensorflow/adanet#4]
I try to run example on Windows 7 (Japanese) .
    https://github.com/tensorflow/adanet/blob/master/adanet/examples/tutorials/adanet_objective.ipynb
And this error occured.

INFO:tensorflow:Encountered end of input during report materialization
INFO:tensorflow:Materialized subnetwork_reports.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 43, in train_and_evaluate
  File "C:\Users\XXXXX\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\estimator\training.py", line 471, in train_and_evaluate
    return executor.run()
  File "C:\Users\XXXXX\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\estimator\training.py", line 610, in run
    return self.run_local()
  File "C:\Users\XXXXX\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\estimator\training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "C:\Anaconda3_5_2\lib\site-packages\adanet\core\estimator.py", line 461,in train
    self._prepare_next_iteration()
  File "C:\Anaconda3_5_2\lib\site-packages\adanet\core\estimator.py", line 569,in _prepare_next_iteration
    tf.estimator.ModeKeys.EVAL, params)
  File "C:\Anaconda3_5_2\lib\site-packages\adanet\core\estimator.py", line 541,in _call_adanet_model_fn
    self._model_fn(features, labels, mode, params)
  File "C:\Anaconda3_5_2\lib\site-packages\adanet\core\estimator.py", line 1083, in _model_fn
    self._materialize_report(current_iteration)
  File "C:\Anaconda3_5_2\lib\site-packages\adanet\core\estimator.py", line 752,in _materialize_report
    materialized_reports)
  File "C:\Anaconda3_5_2\lib\site-packages\adanet\core\report_accessor.py", line 190, in write_iteration_report
    materialized_reports),
  File "C:\Anaconda3_5_2\lib\site-packages\adanet\core\report_accessor.py", line 150, in _create_iteration_report_pb
    iteration_report_pb.subnetwork_reports.extend(subnetwork_report_pb_list)
  File "C:\Anaconda3_5_2\lib\site-packages\adanet\core\report_accessor.py", line 137, in _create_subnetwork_report_proto
    dictionary=materialized_subnetwork_report.metrics)
  File "C:\Anaconda3_5_2\lib\site-packages\adanet\core\report_accessor.py", line 114, in _update_proto_map_from_dict
    field[key].string_value = six.u(value)
ValueError: b"\n\x83\x01\n;adanet/iteration_2/ensemble_2_layer_dnn/architecture/adanetB:\x08\x07\x12\x00B4| b'1_layer_dnn' | b'2_layer_dnn' | b'2_layer_dnn' |J\x08\n\x06\n\x04text" has type str, but isn't valid UTF-8 encoding. Non-UTF-8 strings must be converted to unicode objects before being added.

**Comment by ShettyHarapanahalli** [comment]
I also got same issue on ubuntu 16.04 
ValueError: b"\n\x83\x01\n;adanet/iteration_2/ensemble_3_layer_dnn/architecture/adanetB:\x08\x07\x12\x00B4| b'1_layer_dnn' | b'2_layer_dnn' | b'3_layer_dnn' |J\x08\n\x06\n\x04text" has type str, but isn't valid UTF-8 encoding. Non-UTF-8 strings must be converted to unicode objects before being added.

**Comment by GitHub30** [comment]
Please try with Python 2

**Comment by ShettyHarapanahalli** [comment]
The model started with no errors on python2

**Comment by zhouhao-learning** [comment]
@GitHub30 
How can I use python3 to make the code work? Because python2 is no longer applicable.

**Comment by Efaq** [comment]
Working on Ubuntu 16.02 with python 2, NOT working on Windows 10 with Python 3. I get the same error as reported.
@GitHub30 Is there Python 3 compatibility in the roadmap? As @zhouhao-learning also said, we should stop using Python 2.

**Comment by zhouhao-learning** [comment]
@GitHub30 
Even if I change to a python2 environment, I will still get an error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-7-7612596cd623> in <module>()
     63 
     64 
---> 65 results, _ = train_and_evaluate()
     66 print("Loss:", results["average_loss"])
     67 print("Architecture:", ensemble_architecture(results))

TypeError: 'NoneType' object is not iterable
```

**Comment by Efaq** [comment]
@GitHub30 Does it mean you cannot reproduce the error? Is the pull request mentioned aiming to fix it?
Here is a more detailed specs from my environment, where I still can reproduce the error:
Windows 10, Python 3.6, virtualenv with Tensorflow 1.12.0rc2 and adanet 0.1.0.dev2. Some checkpoints saved, and then the error:
`ValueError: b"\n\x83\x01\n;adanet/iteration_2/ensemble_2_layer_dnn/architecture/adanetB:\x08\x07\x12\x00B4| b'1_layer_dnn' | b'2_layer_dnn' | b'2_layer_dnn' |J\x08\n\x06\n\x04text" has type str, but isn't valid UTF-8 encoding. Non-UTF-8 strings must be converted to unicode objects before being added.
`
